#!/bin/bash
PROJECT_NAME="ia-census"

# Use the Census Reporter API to download updated Census data
URL="http://api.censusreporter.org/1.0/data/show/latest?table_ids"
IA="04000US19"
COUNTIES="050|04000US19"

# Feed topics
# The first variable is the Census table for each topic
# The second is the specific field you want to pull
# For instance, most have a "Total" field we use which is 001 in the data feed
POPULATION="B01003"
FIELD_POPULATION="001"

MEDIAN_AGE="B01002"
FIELD_MEDIAN_AGE="001"

MEDIAN_HOUSEHOLD_INCOME="B19013"
FIELD_MEDIAN_HOUSEHOLD_INCOME="001"

# In this example, we need to divide the Total field
# With the population field to get the percentage
# So we have included a DIVIDE variable
# To indicate which field we need to divide by
POVERTY_STATUS="B17001"
FIELD_POVERTY_STATUS="002"
DIVIDE_POVERTY_STATUS="001"

RACE_WHITE="B02001"
FIELD_RACE_WHITE="002"
DIVIDE_RACE_WHITE="001"

RACE_BLACK="B02001"
FIELD_RACE_BLACK="003"
DIVIDE_RACE_BLACK="001"

RACE_INDIAN="B02001"
FIELD_RACE_INDIAN="004"
DIVIDE_RACE_INDIAN="001"

RACE_ASIAN="B02001"
FIELD_RACE_ASIAN="005"
DIVIDE_RACE_ASIAN="001"

RACE_OTHER="B02001"
FIELD_RACE_OTHER="007"
DIVIDE_RACE_OTHER="001"

RACE_TWO="B02001"
FIELD_RACE_TWO="008"
DIVIDE_RACE_TWO="001"

EDU_LESS_THAN_HS="B06009"
FIELD_EDU_LESS_THAN_HS="002"
DIVIDE_EDU_LESS_THAN_HS="001"

EDU_HS_GRAD="B06009"
FIELD_EDU_HS_GRAD="003"
DIVIDE_EDU_HS_GRAD="001"

EDU_SOME_COLLEGE="B06009"
FIELD_EDU_SOME_COLLEGE="004"
DIVIDE_EDU_SOME_COLLEGE="001"

EDU_BACHELORS="B06009"
FIELD_EDU_BACHELORS="005"
DIVIDE_EDU_BACHELORS="001"

EDU_GRADUATE="B06009"
FIELD_EDU_GRADUATE="006"
DIVIDE_EDU_GRADUATE="001"

INDUSTRY_AG="B08126"
FIELD_INDUSTRY_AG="002"
DIVIDE_INDUSTRY_AG="001"

INDUSTRY_CONSTRUCTION="B08126"
FIELD_INDUSTRY_CONSTRUCTION="003"
DIVIDE_INDUSTRY_CONSTRUCTION="001"

INDUSTRY_MANUFACTURING="B08126"
FIELD_INDUSTRY_MANUFACTURING="004"
DIVIDE_INDUSTRY_MANUFACTURING="001"

INDUSTRY_RETAIL="B08126"
FIELD_INDUSTRY_RETAIL="006"
DIVIDE_INDUSTRY_RETAIL="001"

INDUSTRY_FINANCE="B08126"
FIELD_INDUSTRY_FINANCE="009"
DIVIDE_INDUSTRY_FINANCE="001"

INDUSTRY_EDUCATION="B08126"
FIELD_INDUSTRY_EDUCATION="011"
DIVIDE_INDUSTRY_EDUCATION="001"

INDUSTRY_ARTS="B08126"
FIELD_INDUSTRY_ARTS="012"
DIVIDE_INDUSTRY_ARTS="001"

# Census topics
CENSUS_TOPICS=("POPULATION" "MEDIAN_AGE" "MEDIAN_HOUSEHOLD_INCOME" "POVERTY_STATUS" "RACE_WHITE" "RACE_BLACK" "RACE_INDIAN" "RACE_ASIAN" "RACE_OTHER" "RACE_TWO" "EDU_LESS_THAN_HS" "EDU_HS_GRAD" "EDU_SOME_COLLEGE" "EDU_BACHELORS" "EDU_GRADUATE" "INDUSTRY_AG" "INDUSTRY_CONSTRUCTION" "INDUSTRY_MANUFACTURING" "INDUSTRY_RETAIL" "INDUSTRY_FINANCE" "INDUSTRY_EDUCATION" "INDUSTRY_ARTS")
