CREATE TABLE "matching-cr" (
	"FIRST_NAME" VARCHAR(11) NOT NULL, 
	"LAST_NAME" VARCHAR(19) NOT NULL, 
	"LEGALFIRST" VARCHAR(13) NOT NULL, 
	"LEGALLAST" VARCHAR(19) NOT NULL, 
	"FULL_ADDRESS" VARCHAR(26) NOT NULL, 
	"CITY" VARCHAR(13) NOT NULL, 
	"GENDER" VARCHAR(6) NOT NULL, 
	"PARTY" VARCHAR(3) NOT NULL, 
	"SCHOOL_ELECTION_091013" VARCHAR(4)
);
