CREATE TABLE "04-joco-linn-voters" (
	"REGN_NUM" INTEGER NOT NULL, 
	"FIRST_NAME" VARCHAR(17), 
	"MIDDLE_NAME" VARCHAR(21), 
	"LAST_NAME" VARCHAR(22), 
	"PHONENO" VARCHAR(23), 
	"FULL_ADDRESS" VARCHAR(27), 
	"POST_DIR" VARCHAR(13), 
	"UNIT_TYPE" VARCHAR(6), 
	"UNIT_NUM" VARCHAR(10), 
	"CITY" VARCHAR(13) NOT NULL, 
	"STATE" VARCHAR(12) NOT NULL, 
	"ZIP_CODE" VARCHAR(5) NOT NULL, 
	"VOTERSTATUS" VARCHAR(10) NOT NULL, 
	"PARTY" VARCHAR(8) NOT NULL, 
	"GENDER" VARCHAR(6) NOT NULL, 
	"BIRTHDATE" VARCHAR(10), 
	"SCHOOL_ELECTION_091013" VARCHAR(10)
);
