SELECT Physician_First_Name,Physician_Middle_Name,Physician_Last_Name,Physician_Profile_ID,Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name,Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_State,Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID,Total_Amount_of_Payment_USDollars,Date_of_Payment
FROM data
WHERE Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID = 100000005601
ORDER BY Total_Amount_of_Payment_USDollars DESC
LIMIT 50;