SELECT Physician_First_Name,Physician_Middle_Name,Physician_Last_Name,Physician_Profile_ID,Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name,Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_State,Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID,Total_Amount_of_Payment_USDollars,Date_of_Payment,Category
FROM data
WHERE Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID IN (
	SELECT Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID
	FROM data
	WHERE Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID > 0
	GROUP BY Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID
	ORDER BY SUM( CAST(Total_Amount_of_Payment_USDollars AS REAL) ) DESC
	LIMIT 50
)
ORDER BY Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID DESC;