CREATE TABLE data2015 (
	"GIS_Number" BIGINT NOT NULL, 
	"Doing_Business_As" VARCHAR(58), 
	"Class" VARCHAR(10) NOT NULL, 
	"Map Name" VARCHAR(18) NOT NULL, 
	"Hse#" INTEGER NOT NULL, 
	"Address" VARCHAR(23) NOT NULL, 
	"Deedholder" VARCHAR(31) NOT NULL, 
	"Acres" FLOAT, 
	"Residential Occupancy Type" VARCHAR(24), 
	"Style Descr" VARCHAR(17), 
	"Year Built" INTEGER, 
	"Total Living Area" FLOAT, 
	"Commercial Occupancy Type" VARCHAR(32), 
	"Year Built_2" INTEGER, 
	"Gross Bldg Area" INTEGER, 
	"2015 Land Res" INTEGER NOT NULL, 
	"2015 Land Comm" INTEGER NOT NULL, 
	"2015 Total Land" INTEGER NOT NULL, 
	"2015 Dwlg" INTEGER NOT NULL, 
	"2015 Improv" INTEGER NOT NULL, 
	"2015 Total" INTEGER NOT NULL, 
	"2008 Land" INTEGER, 
	"2008 Dwlg" INTEGER, 
	"2008 Improv" INTEGER, 
	"2008 total" INTEGER, 
	"2016 Land Res" INTEGER, 
	"2016 Land Comm" INTEGER, 
	"2016 Land Total" INTEGER, 
	"2016 Dwlg" INTEGER, 
	"2016 Improv" INTEGER, 
	"2016 Total" INTEGER
);
