CREATE TABLE data2009 (
	"GIS_Number" BIGINT NOT NULL, 
	"Doing Business As" VARCHAR(27), 
	"Class" VARCHAR(10) NOT NULL, 
	"Map Name" VARCHAR(19) NOT NULL, 
	"Hse#" VARCHAR(4), 
	"Address" VARCHAR(23) NOT NULL, 
	"Deedholder" VARCHAR(20) NOT NULL, 
	"Acres" FLOAT, 
	"Residential Occupancy Type" VARCHAR(23), 
	"Style Descr" VARCHAR(29), 
	"Year Built" DATE, 
	"Total Living Area" DATE, 
	"Commercial Occupancy Type" VARCHAR(29), 
	"Year Built_2" INTEGER, 
	"Gross Bldg Area" INTEGER, 
	_unnamed VARCHAR(30), 
	"2009 Land" INTEGER NOT NULL, 
	"2009 Dwlg" INTEGER NOT NULL, 
	"2009 Improv" INTEGER NOT NULL, 
	"2009 Total" INTEGER NOT NULL, 
	"2008 Land" INTEGER, 
	"2008 Dwlg" INTEGER, 
	"2008 Improv" INTEGER, 
	"2008 total" INTEGER, 
	"2016 Land Res" INTEGER, 
	"2016 Land Comm" INTEGER, 
	"2016 Land Total" INTEGER, 
	"2016 Dwlg" INTEGER, 
	"2016 Improv" INTEGER, 
	"2016 Total" INTEGER
);
