CREATE TABLE data2012 (
	"GIS_Number" BIGINT NOT NULL, 
	"Doing_Business_As" VARCHAR(43), 
	"Class" VARCHAR(11) NOT NULL, 
	"Map Name" VARCHAR(20) NOT NULL, 
	"Hse#" INTEGER, 
	"Address" VARCHAR(23) NOT NULL, 
	"Deedholder" VARCHAR(29) NOT NULL, 
	"Acres" FLOAT, 
	"Residential Occupancy Type" VARCHAR(41), 
	"Style Descr" VARCHAR(27), 
	"Year Built" DATE, 
	"Total Living Area" VARCHAR(13), 
	"Commercial Occupancy Type" VARCHAR(34), 
	"Year Built_2" INTEGER, 
	"Gross Bldg Area" DATE, 
	_unnamed VARCHAR(29), 
	"2012 Land Res" INTEGER NOT NULL, 
	"2012 Land Comm" INTEGER NOT NULL, 
	"2012 Land Total" INTEGER NOT NULL, 
	"2012 Dwlg" INTEGER NOT NULL, 
	"2012 Improv" INTEGER NOT NULL, 
	"2012 Total" INTEGER NOT NULL, 
	"2008 Land" INTEGER, 
	"2008 Dwlg" INTEGER, 
	"2008 Improv" INTEGER, 
	"2008 total" INTEGER, 
	"2016 Land Res" INTEGER, 
	"2016 Land Comm" INTEGER, 
	"2016 Land Total" INTEGER, 
	"2016 Dwlg" INTEGER, 
	"2016 Improv" INTEGER, 
	"2016 Total" INTEGER
);
