CREATE TABLE data2008 (
	"GIS_Number" BIGINT NOT NULL, 
	"Doing Business As" VARCHAR(30), 
	"Class" VARCHAR(10) NOT NULL, 
	"Map Name" VARCHAR(7) NOT NULL, 
	"Hse#" VARCHAR(4) NOT NULL, 
	"Address" VARCHAR(23) NOT NULL, 
	"Deedholder" VARCHAR(20) NOT NULL, 
	"Acres" FLOAT, 
	"Residential Occupancy Type" VARCHAR(13), 
	"Style Descr" VARCHAR(17), 
	"Year Built" INTEGER, 
	"Total Living Area" FLOAT, 
	"Commercial Occupancy Type" VARCHAR(29), 
	"Year Built_2" INTEGER, 
	"Gross Bldg Area" INTEGER, 
	_unnamed VARCHAR(29), 
	"2008 Land" INTEGER NOT NULL, 
	"2008 Dwlg" INTEGER NOT NULL, 
	"2008 Improv" INTEGER NOT NULL, 
	"2008 total" INTEGER NOT NULL, 
	"2016 Land Res" INTEGER, 
	"2016 Land Comm" INTEGER, 
	"2016 Land Total" INTEGER, 
	"2016 Dwlg" INTEGER, 
	"2016 Improv" INTEGER, 
	"2016 Total" INTEGER
);
