CREATE TABLE data2014 (
	"GIS_Number" BIGINT NOT NULL, 
	"Doing_Business_As" VARCHAR(57), 
	"Class" VARCHAR(11) NOT NULL, 
	"Map Name" VARCHAR(18) NOT NULL, 
	"Hse#" INTEGER, 
	"Address" VARCHAR(23) NOT NULL, 
	"Deedholder" VARCHAR(31) NOT NULL, 
	"Acres" FLOAT, 
	"Residential Occupancy Type" VARCHAR(24), 
	"Style Descr" VARCHAR(33), 
	"Year Built" INTEGER, 
	"Total Living Area" DATE, 
	"Commercial Occupancy Type" VARCHAR(34), 
	"Year Built_2" INTEGER, 
	"Gross Bldg Area" INTEGER, 
	_unnamed VARCHAR(29), 
	"2014 Land Res" INTEGER NOT NULL, 
	"2014 Land Comm" INTEGER NOT NULL, 
	"2014 Land Total" INTEGER NOT NULL, 
	"2014 Dwlg" INTEGER NOT NULL, 
	"2014 Improv" INTEGER NOT NULL, 
	"2014 Total" INTEGER NOT NULL, 
	"2008 Land" INTEGER, 
	"2008 Dwlg" INTEGER, 
	"2008 Improv" INTEGER, 
	"2008 total" INTEGER, 
	"2016 Land Res" INTEGER, 
	"2016 Land Comm" INTEGER, 
	"2016 Land Total" INTEGER, 
	"2016 Dwlg" INTEGER, 
	"2016 Improv" INTEGER, 
	"2016 Total" INTEGER
);
