CREATE TABLE data2011 (
	"GIS_Number" BIGINT NOT NULL, 
	"Doing_Business_As" VARCHAR(43), 
	"Class" VARCHAR(11) NOT NULL, 
	"Map Name" VARCHAR(20) NOT NULL, 
	"Hse#" VARCHAR(4), 
	"Address" VARCHAR(23) NOT NULL, 
	"Deedholder" VARCHAR(53) NOT NULL, 
	"Acres" FLOAT, 
	"Residential Occupancy Type" VARCHAR(41), 
	"Style Descr" VARCHAR(27), 
	"Year Built" DATE, 
	"Total Living Area" VARCHAR(12), 
	"Commercial Occupancy Type" VARCHAR(29), 
	"Year Built_2" INTEGER, 
	"Gross Bldg Area" INTEGER, 
	"2011 Land Res" INTEGER NOT NULL, 
	"2011 Land Comm" INTEGER NOT NULL, 
	"2011 Land Total" INTEGER NOT NULL, 
	"2011 Dwlg" INTEGER NOT NULL, 
	"2011 Improv" INTEGER NOT NULL, 
	"2011 Total" INTEGER NOT NULL, 
	"2008 Land" INTEGER, 
	"2008 Dwlg" INTEGER, 
	"2008 Improv" INTEGER, 
	"2008 total" INTEGER, 
	"2016 Land Res" INTEGER, 
	"2016 Land Comm" INTEGER, 
	"2016 Land Total" INTEGER, 
	"2016 Dwlg" INTEGER, 
	"2016 Improv" INTEGER, 
	"2016 Total" INTEGER
);
