CREATE TABLE data2016 (
	"GIS_Number" BIGINT NOT NULL, 
	"Doing_Business_As" VARCHAR(58), 
	"Class" VARCHAR(10) NOT NULL, 
	"Map Name" VARCHAR(13) NOT NULL, 
	"Hse#" INTEGER NOT NULL, 
	"Address" VARCHAR(23) NOT NULL, 
	"Deedholder" VARCHAR(32) NOT NULL, 
	"Acres" FLOAT, 
	"Residential Occupancy Type" VARCHAR(24), 
	"Style Descr" VARCHAR(17), 
	"Year Built" INTEGER, 
	"Total Living Area" FLOAT, 
	"Commercial Occupancy Type" VARCHAR(16), 
	"Year Built_2" INTEGER, 
	"Gross Bldg Area" INTEGER, 
	"2008 Land" INTEGER, 
	"2008 Dwlg" INTEGER, 
	"2008 Improv" INTEGER, 
	"2008 total" INTEGER, 
	"2016 Land Res" INTEGER NOT NULL, 
	"2016 Land Comm" INTEGER NOT NULL, 
	"2016 Land Total" INTEGER NOT NULL, 
	"2016 Dwlg" INTEGER NOT NULL, 
	"2016 Improv" INTEGER NOT NULL, 
	"2016 Total" INTEGER NOT NULL
);
